language: node_js
notifications:
  email: false
node_js: 12
addons:
  ssh_known_hosts: sudokugeni.us
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: main
